# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - main: ./cmd/rxtls
    binary: rxtls
    id: rxtls
    env:
      - CGO_ENABLED=0
    goos: [windows, linux, darwin, freebsd]
    goarch: [amd64, '386', arm, arm64]
    goarm: ['6', '7']
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: rxtls
    ids: [rxtls]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

snapshot:
  version_template: '{{ incpatch .Version }}-dev'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - typo
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Code Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Other
      order: 999

release:
  github:
    owner: x-stp
    name: rxtls
  prerelease: auto
  draft: false
  name_template: '{{ .Tag }}'
  header: |
    ## rxtls {{ .Tag }}
    
    High-Performance Certificate Transparency Processor
  footer: |
    ## Installation
    
    ### Binary
    Download the appropriate binary for your platform from the assets below.
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew tap x-stp/rxtls
    brew install rxtls
    ```
    
    ### Docker
    ```bash
    docker pull ghcr.io/x-stp/rxtls:{{ .Tag }}
    ```
    
    **Full documentation**: https://github.com/x-stp/rxtls#readme

dockers:
  - image_templates:
      - 'ghcr.io/x-stp/{{ .ProjectName }}:{{ .Tag }}-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:latest-amd64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/amd64'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--label=org.opencontainers.image.source=https://github.com/x-stp/rxtls'
      - '--label=org.opencontainers.image.licenses=AGPL-3.0'
    goarch: amd64
    goos: linux
    
  - image_templates:
      - 'ghcr.io/x-stp/{{ .ProjectName }}:{{ .Tag }}-arm64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}-arm64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:latest-arm64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/arm64'
      - '--label=org.opencontainers.image.created={{ .Date }}'
      - '--label=org.opencontainers.image.title={{ .ProjectName }}'
      - '--label=org.opencontainers.image.revision={{ .FullCommit }}'
      - '--label=org.opencontainers.image.version={{ .Version }}'
      - '--label=org.opencontainers.image.source=https://github.com/x-stp/rxtls'
      - '--label=org.opencontainers.image.licenses=AGPL-3.0'
    goarch: arm64
    goos: linux

docker_manifests:
  - name_template: 'ghcr.io/x-stp/{{ .ProjectName }}:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/x-stp/{{ .ProjectName }}:{{ .Tag }}-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:{{ .Tag }}-arm64'
      
  - name_template: 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64'
      
  - name_template: 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}'
    image_templates:
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:v{{ .Major }}-arm64'
      
  - name_template: 'ghcr.io/x-stp/{{ .ProjectName }}:latest'
    image_templates:
      - 'ghcr.io/x-stp/{{ .ProjectName }}:latest-amd64'
      - 'ghcr.io/x-stp/{{ .ProjectName }}:latest-arm64'

homebrew_casks:
  - repository:
      owner: x-stp
      name: homebrew-rxtls
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    name: rxtls
    directory: Casks
    homepage: 'https://github.com/x-stp/rxtls'
    description: 'High-Performance Certificate Transparency Processor'
    license: 'AGPL-3.0'
    conflicts:
      - formula: rxtls

nfpms:
  - id: rxtls
    package_name: rxtls
    formats:
      - deb
      - rpm
      - apk
    vendor: 'x-stp'
    homepage: 'https://github.com/x-stp/rxtls'
    maintainer: 'Pepijn van der Stap <rxtls@vanderstap.info>'
    description: 'High-Performance Certificate Transparency Processor'
    license: 'AGPL-3.0'
    dependencies:
      - ca-certificates
    section: net
    priority: optional
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/rxtls/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/rxtls/README.md