name: PowerPC CI

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-ppc64le:
    name: Build on ppc64le
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install QEMU
        run: sudo apt-get install -y qemu-user-static

      - name: Cross-compile to ppc64le
        run: |
          GOARCH=ppc64le GOOS=linux go build -v ./...
