name: PowerPC CI

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-ppc64le:
    name: Build on ppc64le
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@41dfa10ca2ca416f9bf1cf0b1e92d381cdfe9d0c # v4
        with:
          go-version-file: go.mod

      - name: Install QEMU
        run: sudo apt-get install -y qemu-user-static

      - name: Cross-compile to ppc64le
        run: |
          GOARCH=ppc64le GOOS=linux go build -v ./...
